name: ReOp
main: reop\Main
version: 1.0.0
api: [1.0.0, 2.0.0]
load: POSTWORLD
author: TheDeibo
description: Allows the user to be reoped IF they are on the Config
commands:
  reop:
    description: Reop's yourself if your on the list
    permission: reop.reop
permissions:
  reop.reop:
    description: Allows the user to be reoped IF they are on the Config.
    default: true
